In [1]:
import pandas as pd
from typing import Iterable
from helpers import get_request

In [2]:
def get_article_contents(links: Iterable[str]):
    get_url_from_link = lambda link : f"https://www.ufc.com/{link}"

    link_len = len(links)

    for (i, link) in enumerate(links):
        if i % 10 == 0:
            print("Getting page", i, "/", link_len)
    
        try:
            response = get_request(get_url_from_link(link))
            yield response.text
        except Exception as e:
            print("Error getting page", link)
            print(e)

            yield None

In [3]:
filename = "./article_links_06-11-25_20-40-38"
articles_df = pd.read_csv(f"{filename}.csv")
articles_df

,link,type,time_ago,headline
0,/news/gabriel-bonfim-leveled-up-legend-ufc-veg...,Athletes,4 hours ago,Gabriel Bonfim | Leveled Up By A Legend
1,/news/chris-padilla-blocking-out-the-noise-ufc...,Athletes,5 hours ago,Chris Padilla | Blocking Out The Noise
2,/news/matt-schnell-honest-excited-and-dangerou...,Athletes,5 hours ago,"Matt Schnell | Honest, Excited, And Dangerous"
3,/video/152387,Interviews,5 hours ago,Zachary Reese Fight Week Interview | UFC Fight...
4,/news/tecia-pennington-crossroad-ufc-fight-nig...,Athletes,5 hours ago,Tecia Pennington | At A Crossroad
...,...,...,...,...
134,/video/152070,Interviews,1 week ago,Mackenzie Dern Talks With John Gooden | UFC 321
135,/video/152069,Interviews,1 week ago,Ciryl Gane Talks With John Gooden | UFC 321
136,/video/152067,Interviews,1 week ago,Tom Aspinall Talks With John Gooden | UFC 321
137,/news/seriously-do-not-blink-when-tom-aspinall...,Athletes,1 week ago,Seriously: Do Not Blink When Tom Aspinall And ...
138,/video/152054,Power Slap,1 week ago,Power Slap 16: Wolverine vs Klingbeil | Full E...

In [4]:
articles_with_correct_type = articles_df[
    ((articles_df["type"] == "Results")
    | (articles_df["type"] == "Athletes")
    | (articles_df["type"] == "Fight Coverage")
    | (articles_df["type"] == "Fight Preview"))
    & (~articles_df["link"].str.contains("video"))
]
articles_with_correct_type

,link,type,time_ago,headline
0,/news/gabriel-bonfim-leveled-up-legend-ufc-veg...,Athletes,4 hours ago,Gabriel Bonfim | Leveled Up By A Legend
1,/news/chris-padilla-blocking-out-the-noise-ufc...,Athletes,5 hours ago,Chris Padilla | Blocking Out The Noise
2,/news/matt-schnell-honest-excited-and-dangerou...,Athletes,5 hours ago,"Matt Schnell | Honest, Excited, And Dangerous"
4,/news/tecia-pennington-crossroad-ufc-fight-nig...,Athletes,5 hours ago,Tecia Pennington | At A Crossroad
6,/news/uros-medic-back-track-ufc-fight-night-bo...,Athletes,5 hours ago,Uroš Medić Is Back On Track
8,/news/randy-brown-something-bigger-ufc-fight-n...,Athletes,11 hours ago,Randy Brown | Something Bigger
16,/news/joseph-morales-all-way-back-ufc-vegas-11...,Athletes,1 day ago,Joseph Morales | All The Way Back
22,/news/malcolm-wellmaker-built-ground-bantamwei...,Athletes,1 day ago,Malcolm Wellmaker | Built From The Ground Up
24,/news/christian-leroy-duncan-settled-and-start...,Athletes,1 day ago,Christian Leroy Duncan | Settled In And Starti...
28,/news/adrian-yanez-reloaded-ufc-vegas-111,Athletes,3 weeks hence,Adrian Yanez | Reloaded
30,/news/fighters-on-the-rise-ufc-fight-night-bon...,Athletes,3 days ago,Fighters On The Rise | UFC Fight Night: Bonfim...
33,/news/fight-fight-preview-ufc-fight-night-bonf...,Fight Coverage,3 days ago,Fight By Fight Preview | UFC Fight Night: Bonf...
35,/news/scorecard-ufc-fight-night-garcia-vs-onama,Fight Coverage,4 days ago,The Scorecard | UFC Fight Night: Garcia vs Onama
36,/news/ufc-fight-night-garcia-vs-onama-main-car...,Results,5 days ago,Main Card Results | UFC Fight Night: Garcia vs...
38,/news/bonus-coverage-2025-performance-fight-of...,Results,4 days ago,Bonus Coverage | UFC Fight Night: Garcia vs Onama
53,/news/ufc-fight-night-garcia-vs-onama-prelim-r...,Results,4 days ago,Prelim Results | UFC Fight Night: Garcia vs Onama
62,/news/fight-by-fight-preview-ufc-fight-night-g...,Fight Coverage,5 days ago,UFC Tonight: Fight By Fight Preview | UFC Fight…
64,/news/yadier-del-valle-no-fear-ufc-vegas-110,Athletes,6 days ago,Yadier del Valle | No Fear
69,/news/themba-gorimbo-welcome-to-the-mamba-show...,Athletes,6 days ago,Themba Gorimbo: ‘Welcome To The Mamba Show’
70,/news/the-tao-of-allan-nascimento-ufc-vegas-110,Athletes,1 week ago,The Tao Of Allan Nascimento
71,/news/phil-rowe-tired-of-fighting-himself-ufc-...,Athletes,1 week ago,Phil Rowe | Tired of Fighting Himself
72,/news/waldo-cortes-acosta-be-more-waldo-ufc-ve...,Athletes,1 week ago,Waldo Cortes Acosta | Be More Waldo
73,/news/alice-ardelean-is-planning-her-big-move-...,Athletes,1 week ago,Alice Ardelean Is Planning Her Big Move
74,/news/ante-delija-making-waves,Athletes,1 week ago,Ante Delija | Making Waves
75,/news/ketlen-vieira-ready-claim-title-ufc-vega...,Athletes,1 week ago,Ketlen Vieira Is Ready To Claim Her Title Shot
80,/news/norma-dumont-done-waiting-around-ufc-fig...,Athletes,1 week ago,Norma Dumont Is Done Waiting Around
82,/news/david-onama-excited-but-also-expected-ve...,Athletes,1 week ago,"David Onama | Excited, But Also Expected"
87,/news/donte-johnson-clocking-in-ufc-vegas-110,Athletes,1 week ago,Donte Johnson | Clocking In
89,/news/10-get-ready-for-a-november-to-remember-...,Athletes,1 week ago,The 10 | Get Ready For A November To Remember ...
94,/news/fighters-rise-ufc-fight-night-garcia-vs-...,Athletes,1 week ago,Fighters On The Rise | UFC Fight Night: Garcia...
97,/news/steve-garcia-real-recognizes-real-ufc-fi...,Athletes,1 week ago,Steve Garcia | Real Recognizes Real
103,/news/monthly-report-october-2025-ufc-jourdain...,Athletes,1 week ago,Monthly Report | October 2025
104,/news/bigger-picture-ufc-321-aspinall-vs-gane,Fight Coverage,1 week ago,The Bigger Picture | UFC 321: Aspinall vs Gane
110,/news/ufc-321-aspinall-vs-gane-event-tonight-m...,Results,1 week ago,Main Card Results | UFC 321: Aspinall vs Gane
122,/news/ufc-321-aspinall-vs-gane-event-tonight-p...,Results,1 week ago,Prelim Results | UFC 321: Aspinall vs Gane
129,/news/fight-by-fight-preview-ufc-321-aspinall-...,Fight Coverage,1 week ago,UFC Today: Fight By Fight Preview | UFC 321:…
130,/news/junyong-park-hungry-for-more-ufc-321,Athletes,1 week ago,Junyong Park | Hungry For More
137,/news/seriously-do-not-blink-when-tom-aspinall...,Athletes,1 week ago,Seriously: Do Not Blink When Tom Aspinall And ...

In [5]:
articles_to_scrape = articles_with_correct_type[articles_with_correct_type["link"].str.contains("news")].copy()
articles_to_scrape

,link,type,time_ago,headline
0,/news/gabriel-bonfim-leveled-up-legend-ufc-veg...,Athletes,4 hours ago,Gabriel Bonfim | Leveled Up By A Legend
1,/news/chris-padilla-blocking-out-the-noise-ufc...,Athletes,5 hours ago,Chris Padilla | Blocking Out The Noise
2,/news/matt-schnell-honest-excited-and-dangerou...,Athletes,5 hours ago,"Matt Schnell | Honest, Excited, And Dangerous"
4,/news/tecia-pennington-crossroad-ufc-fight-nig...,Athletes,5 hours ago,Tecia Pennington | At A Crossroad
6,/news/uros-medic-back-track-ufc-fight-night-bo...,Athletes,5 hours ago,Uroš Medić Is Back On Track
8,/news/randy-brown-something-bigger-ufc-fight-n...,Athletes,11 hours ago,Randy Brown | Something Bigger
16,/news/joseph-morales-all-way-back-ufc-vegas-11...,Athletes,1 day ago,Joseph Morales | All The Way Back
22,/news/malcolm-wellmaker-built-ground-bantamwei...,Athletes,1 day ago,Malcolm Wellmaker | Built From The Ground Up
24,/news/christian-leroy-duncan-settled-and-start...,Athletes,1 day ago,Christian Leroy Duncan | Settled In And Starti...
28,/news/adrian-yanez-reloaded-ufc-vegas-111,Athletes,3 weeks hence,Adrian Yanez | Reloaded
30,/news/fighters-on-the-rise-ufc-fight-night-bon...,Athletes,3 days ago,Fighters On The Rise | UFC Fight Night: Bonfim...
33,/news/fight-fight-preview-ufc-fight-night-bonf...,Fight Coverage,3 days ago,Fight By Fight Preview | UFC Fight Night: Bonf...
35,/news/scorecard-ufc-fight-night-garcia-vs-onama,Fight Coverage,4 days ago,The Scorecard | UFC Fight Night: Garcia vs Onama
36,/news/ufc-fight-night-garcia-vs-onama-main-car...,Results,5 days ago,Main Card Results | UFC Fight Night: Garcia vs...
38,/news/bonus-coverage-2025-performance-fight-of...,Results,4 days ago,Bonus Coverage | UFC Fight Night: Garcia vs Onama
53,/news/ufc-fight-night-garcia-vs-onama-prelim-r...,Results,4 days ago,Prelim Results | UFC Fight Night: Garcia vs Onama
62,/news/fight-by-fight-preview-ufc-fight-night-g...,Fight Coverage,5 days ago,UFC Tonight: Fight By Fight Preview | UFC Fight…
64,/news/yadier-del-valle-no-fear-ufc-vegas-110,Athletes,6 days ago,Yadier del Valle | No Fear
69,/news/themba-gorimbo-welcome-to-the-mamba-show...,Athletes,6 days ago,Themba Gorimbo: ‘Welcome To The Mamba Show’
70,/news/the-tao-of-allan-nascimento-ufc-vegas-110,Athletes,1 week ago,The Tao Of Allan Nascimento
71,/news/phil-rowe-tired-of-fighting-himself-ufc-...,Athletes,1 week ago,Phil Rowe | Tired of Fighting Himself
72,/news/waldo-cortes-acosta-be-more-waldo-ufc-ve...,Athletes,1 week ago,Waldo Cortes Acosta | Be More Waldo
73,/news/alice-ardelean-is-planning-her-big-move-...,Athletes,1 week ago,Alice Ardelean Is Planning Her Big Move
74,/news/ante-delija-making-waves,Athletes,1 week ago,Ante Delija | Making Waves
75,/news/ketlen-vieira-ready-claim-title-ufc-vega...,Athletes,1 week ago,Ketlen Vieira Is Ready To Claim Her Title Shot
80,/news/norma-dumont-done-waiting-around-ufc-fig...,Athletes,1 week ago,Norma Dumont Is Done Waiting Around
82,/news/david-onama-excited-but-also-expected-ve...,Athletes,1 week ago,"David Onama | Excited, But Also Expected"
87,/news/donte-johnson-clocking-in-ufc-vegas-110,Athletes,1 week ago,Donte Johnson | Clocking In
89,/news/10-get-ready-for-a-november-to-remember-...,Athletes,1 week ago,The 10 | Get Ready For A November To Remember ...
94,/news/fighters-rise-ufc-fight-night-garcia-vs-...,Athletes,1 week ago,Fighters On The Rise | UFC Fight Night: Garcia...
97,/news/steve-garcia-real-recognizes-real-ufc-fi...,Athletes,1 week ago,Steve Garcia | Real Recognizes Real
103,/news/monthly-report-october-2025-ufc-jourdain...,Athletes,1 week ago,Monthly Report | October 2025
104,/news/bigger-picture-ufc-321-aspinall-vs-gane,Fight Coverage,1 week ago,The Bigger Picture | UFC 321: Aspinall vs Gane
110,/news/ufc-321-aspinall-vs-gane-event-tonight-m...,Results,1 week ago,Main Card Results | UFC 321: Aspinall vs Gane
122,/news/ufc-321-aspinall-vs-gane-event-tonight-p...,Results,1 week ago,Prelim Results | UFC 321: Aspinall vs Gane
129,/news/fight-by-fight-preview-ufc-321-aspinall-...,Fight Coverage,1 week ago,UFC Today: Fight By Fight Preview | UFC 321:…
130,/news/junyong-park-hungry-for-more-ufc-321,Athletes,1 week ago,Junyong Park | Hungry For More
137,/news/seriously-do-not-blink-when-tom-aspinall...,Athletes,1 week ago,Seriously: Do Not Blink When Tom Aspinall And ...

In [6]:
contents = [page for page in get_article_contents(articles_to_scrape["link"])]
print("Got", len([page for page in contents if page is not None]), "page contents")

Getting page 0 / 38
Getting page 10 / 38
Getting page 20 / 38
Getting page 30 / 38
Got 38 page contents

In [7]:
articles_to_scrape["content"] = contents
articles_to_scrape

,link,type,time_ago,headline,content
0,/news/gabriel-bonfim-leveled-up-legend-ufc-veg...,Athletes,4 hours ago,Gabriel Bonfim | Leveled Up By A Legend,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
1,/news/chris-padilla-blocking-out-the-noise-ufc...,Athletes,5 hours ago,Chris Padilla | Blocking Out The Noise,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
2,/news/matt-schnell-honest-excited-and-dangerou...,Athletes,5 hours ago,"Matt Schnell | Honest, Excited, And Dangerous","\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
4,/news/tecia-pennington-crossroad-ufc-fight-nig...,Athletes,5 hours ago,Tecia Pennington | At A Crossroad,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
6,/news/uros-medic-back-track-ufc-fight-night-bo...,Athletes,5 hours ago,Uroš Medić Is Back On Track,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
8,/news/randy-brown-something-bigger-ufc-fight-n...,Athletes,11 hours ago,Randy Brown | Something Bigger,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
16,/news/joseph-morales-all-way-back-ufc-vegas-11...,Athletes,1 day ago,Joseph Morales | All The Way Back,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
22,/news/malcolm-wellmaker-built-ground-bantamwei...,Athletes,1 day ago,Malcolm Wellmaker | Built From The Ground Up,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
24,/news/christian-leroy-duncan-settled-and-start...,Athletes,1 day ago,Christian Leroy Duncan | Settled In And Starti...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
28,/news/adrian-yanez-reloaded-ufc-vegas-111,Athletes,3 weeks hence,Adrian Yanez | Reloaded,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
30,/news/fighters-on-the-rise-ufc-fight-night-bon...,Athletes,3 days ago,Fighters On The Rise | UFC Fight Night: Bonfim...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
33,/news/fight-fight-preview-ufc-fight-night-bonf...,Fight Coverage,3 days ago,Fight By Fight Preview | UFC Fight Night: Bonf...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
35,/news/scorecard-ufc-fight-night-garcia-vs-onama,Fight Coverage,4 days ago,The Scorecard | UFC Fight Night: Garcia vs Onama,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
36,/news/ufc-fight-night-garcia-vs-onama-main-car...,Results,5 days ago,Main Card Results | UFC Fight Night: Garcia vs...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
38,/news/bonus-coverage-2025-performance-fight-of...,Results,4 days ago,Bonus Coverage | UFC Fight Night: Garcia vs Onama,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
53,/news/ufc-fight-night-garcia-vs-onama-prelim-r...,Results,4 days ago,Prelim Results | UFC Fight Night: Garcia vs Onama,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
62,/news/fight-by-fight-preview-ufc-fight-night-g...,Fight Coverage,5 days ago,UFC Tonight: Fight By Fight Preview | UFC Fight…,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
64,/news/yadier-del-valle-no-fear-ufc-vegas-110,Athletes,6 days ago,Yadier del Valle | No Fear,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
69,/news/themba-gorimbo-welcome-to-the-mamba-show...,Athletes,6 days ago,Themba Gorimbo: ‘Welcome To The Mamba Show’,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
70,/news/the-tao-of-allan-nascimento-ufc-vegas-110,Athletes,1 week ago,The Tao Of Allan Nascimento,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
71,/news/phil-rowe-tired-of-fighting-himself-ufc-...,Athletes,1 week ago,Phil Rowe | Tired of Fighting Himself,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
72,/news/waldo-cortes-acosta-be-more-waldo-ufc-ve...,Athletes,1 week ago,Waldo Cortes Acosta | Be More Waldo,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
73,/news/alice-ardelean-is-planning-her-big-move-...,Athletes,1 week ago,Alice Ardelean Is Planning Her Big Move,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
74,/news/ante-delija-making-waves,Athletes,1 week ago,Ante Delija | Making Waves,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
75,/news/ketlen-vieira-ready-claim-title-ufc-vega...,Athletes,1 week ago,Ketlen Vieira Is Ready To Claim Her Title Shot,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
80,/news/norma-dumont-done-waiting-around-ufc-fig...,Athletes,1 week ago,Norma Dumont Is Done Waiting Around,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
82,/news/david-onama-excited-but-also-expected-ve...,Athletes,1 week ago,"David Onama | Excited, But Also Expected","\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
87,/news/donte-johnson-clocking-in-ufc-vegas-110,Athletes,1 week ago,Donte Johnson | Clocking In,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
89,/news/10-get-ready-for-a-november-to-remember-...,Athletes,1 week ago,The 10 | Get Ready For A November To Remember ...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
94,/news/fighters-rise-ufc-fight-night-garcia-vs-...,Athletes,1 week ago,Fighters On The Rise | UFC Fight Night: Garcia...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
97,/news/steve-garcia-real-recognizes-real-ufc-fi...,Athletes,1 week ago,Steve Garcia | Real Recognizes Real,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
103,/news/monthly-report-october-2025-ufc-jourdain...,Athletes,1 week ago,Monthly Report | October 2025,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
104,/news/bigger-picture-ufc-321-aspinall-vs-gane,Fight Coverage,1 week ago,The Bigger Picture | UFC 321: Aspinall vs Gane,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
110,/news/ufc-321-aspinall-vs-gane-event-tonight-m...,Results,1 week ago,Main Card Results | UFC 321: Aspinall vs Gane,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
122,/news/ufc-321-aspinall-vs-gane-event-tonight-p...,Results,1 week ago,Prelim Results | UFC 321: Aspinall vs Gane,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
129,/news/fight-by-fight-preview-ufc-321-aspinall-...,Fight Coverage,1 week ago,UFC Today: Fight By Fight Preview | UFC 321:…,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
130,/news/junyong-park-hungry-for-more-ufc-321,Athletes,1 week ago,Junyong Park | Hungry For More,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
137,/news/seriously-do-not-blink-when-tom-aspinall...,Athletes,1 week ago,Seriously: Do Not Blink When Tom Aspinall And ...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."

In [8]:
contents_filename = f"{filename}_with_contents.csv"
articles_to_scrape\
    .set_index("link")\
    .to_csv(contents_filename)

print("Saved article contents to", contents_filename)

Saved article contents to ./article_links_06-11-25_20-40-38_with_contents.csv