In [1]:
import os
import re
from datetime import datetime
import pandas as pd
from bs4 import BeautifulSoup
from itertools import chain
from typing import Iterable
from helpers import get_page_name

In [2]:
csv_filename = "./article_links_06-11-25_20-40-38_with_contents"
articles_df = pd.read_csv(f"{csv_filename}.csv")
articles_df

,link,type,time_ago,headline,content
0,/news/gabriel-bonfim-leveled-up-legend-ufc-veg...,Athletes,4 hours ago,Gabriel Bonfim | Leveled Up By A Legend,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
1,/news/chris-padilla-blocking-out-the-noise-ufc...,Athletes,5 hours ago,Chris Padilla | Blocking Out The Noise,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
2,/news/matt-schnell-honest-excited-and-dangerou...,Athletes,5 hours ago,"Matt Schnell | Honest, Excited, And Dangerous","\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
3,/news/tecia-pennington-crossroad-ufc-fight-nig...,Athletes,5 hours ago,Tecia Pennington | At A Crossroad,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
4,/news/uros-medic-back-track-ufc-fight-night-bo...,Athletes,5 hours ago,Uroš Medić Is Back On Track,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
5,/news/randy-brown-something-bigger-ufc-fight-n...,Athletes,11 hours ago,Randy Brown | Something Bigger,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
6,/news/joseph-morales-all-way-back-ufc-vegas-11...,Athletes,1 day ago,Joseph Morales | All The Way Back,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
7,/news/malcolm-wellmaker-built-ground-bantamwei...,Athletes,1 day ago,Malcolm Wellmaker | Built From The Ground Up,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
8,/news/christian-leroy-duncan-settled-and-start...,Athletes,1 day ago,Christian Leroy Duncan | Settled In And Starti...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
9,/news/adrian-yanez-reloaded-ufc-vegas-111,Athletes,3 weeks hence,Adrian Yanez | Reloaded,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
10,/news/fighters-on-the-rise-ufc-fight-night-bon...,Athletes,3 days ago,Fighters On The Rise | UFC Fight Night: Bonfim...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
11,/news/fight-fight-preview-ufc-fight-night-bonf...,Fight Coverage,3 days ago,Fight By Fight Preview | UFC Fight Night: Bonf...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
12,/news/scorecard-ufc-fight-night-garcia-vs-onama,Fight Coverage,4 days ago,The Scorecard | UFC Fight Night: Garcia vs Onama,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
13,/news/ufc-fight-night-garcia-vs-onama-main-car...,Results,5 days ago,Main Card Results | UFC Fight Night: Garcia vs...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
14,/news/bonus-coverage-2025-performance-fight-of...,Results,4 days ago,Bonus Coverage | UFC Fight Night: Garcia vs Onama,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
15,/news/ufc-fight-night-garcia-vs-onama-prelim-r...,Results,4 days ago,Prelim Results | UFC Fight Night: Garcia vs Onama,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
16,/news/fight-by-fight-preview-ufc-fight-night-g...,Fight Coverage,5 days ago,UFC Tonight: Fight By Fight Preview | UFC Fight…,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
17,/news/yadier-del-valle-no-fear-ufc-vegas-110,Athletes,6 days ago,Yadier del Valle | No Fear,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
18,/news/themba-gorimbo-welcome-to-the-mamba-show...,Athletes,6 days ago,Themba Gorimbo: ‘Welcome To The Mamba Show’,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
19,/news/the-tao-of-allan-nascimento-ufc-vegas-110,Athletes,1 week ago,The Tao Of Allan Nascimento,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
20,/news/phil-rowe-tired-of-fighting-himself-ufc-...,Athletes,1 week ago,Phil Rowe | Tired of Fighting Himself,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
21,/news/waldo-cortes-acosta-be-more-waldo-ufc-ve...,Athletes,1 week ago,Waldo Cortes Acosta | Be More Waldo,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
22,/news/alice-ardelean-is-planning-her-big-move-...,Athletes,1 week ago,Alice Ardelean Is Planning Her Big Move,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
23,/news/ante-delija-making-waves,Athletes,1 week ago,Ante Delija | Making Waves,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
24,/news/ketlen-vieira-ready-claim-title-ufc-vega...,Athletes,1 week ago,Ketlen Vieira Is Ready To Claim Her Title Shot,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
25,/news/norma-dumont-done-waiting-around-ufc-fig...,Athletes,1 week ago,Norma Dumont Is Done Waiting Around,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
26,/news/david-onama-excited-but-also-expected-ve...,Athletes,1 week ago,"David Onama | Excited, But Also Expected","\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
27,/news/donte-johnson-clocking-in-ufc-vegas-110,Athletes,1 week ago,Donte Johnson | Clocking In,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
28,/news/10-get-ready-for-a-november-to-remember-...,Athletes,1 week ago,The 10 | Get Ready For A November To Remember ...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
29,/news/fighters-rise-ufc-fight-night-garcia-vs-...,Athletes,1 week ago,Fighters On The Rise | UFC Fight Night: Garcia...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
30,/news/steve-garcia-real-recognizes-real-ufc-fi...,Athletes,1 week ago,Steve Garcia | Real Recognizes Real,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
31,/news/monthly-report-october-2025-ufc-jourdain...,Athletes,1 week ago,Monthly Report | October 2025,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
32,/news/bigger-picture-ufc-321-aspinall-vs-gane,Fight Coverage,1 week ago,The Bigger Picture | UFC 321: Aspinall vs Gane,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
33,/news/ufc-321-aspinall-vs-gane-event-tonight-m...,Results,1 week ago,Main Card Results | UFC 321: Aspinall vs Gane,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
34,/news/ufc-321-aspinall-vs-gane-event-tonight-p...,Results,1 week ago,Prelim Results | UFC 321: Aspinall vs Gane,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
35,/news/fight-by-fight-preview-ufc-321-aspinall-...,Fight Coverage,1 week ago,UFC Today: Fight By Fight Preview | UFC 321:…,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
36,/news/junyong-park-hungry-for-more-ufc-321,Athletes,1 week ago,Junyong Park | Hungry For More,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."
37,/news/seriously-do-not-blink-when-tom-aspinall...,Athletes,1 week ago,Seriously: Do Not Blink When Tom Aspinall And ...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca..."

In [3]:
author_pattern = r"By ([A-Za-z\s.]+).*"
social_media_pattern = r"@([A-Za-z]+)"
text_classes = ["e-p--initial", "field--name-text"]

def get_page_datas(page_contents: Iterable[str]):
    soups = [BeautifulSoup(content, "html.parser") for content in page_contents]

    def get_titles():
        for soup in soups:
            title_element = soup.find("meta", property="og:title")
            yield title_element.get("content") if title_element else None
    
    def get_descriptions():
        for soup in soups:
            description_element = soup.find("meta", property="og:description")
            yield description_element.get("content") if description_element else None
    
    def get_published_times():
        for soup in soups:
            published_time_element = soup.find("meta", property="article:published_time")
            yield datetime.fromisoformat(published_time_element.get("content"))\
                if published_time_element\
                else None
    
    def get_modified_times():
        for soup in soups:
            modified_time_element = soup.find("meta", property="article:modified_time")
            yield datetime.fromisoformat(modified_time_element.get("content"))\
                if modified_time_element\
                else None

    def get_authors():
        for soup in soups:
            credit_element = soup.find("div", "c-hero__article-credit")

            if credit_element:
                credit = credit_element.text.strip().replace("\n", "")
                author_match = re.search(author_pattern, credit)
                yield author_match.group(1).strip() if author_match else None
            else:
                yield None

    def get_social_medias():
        for soup in soups:
            credit_element = soup.find("div", "c-hero__article-credit")

            if credit_element:
                credit = credit_element.text.strip().replace("\n", "")
                social_media_match = re.search(social_media_pattern, credit)
                yield social_media_match.group(1).strip() if social_media_match else None
            else:
                yield None
    
    def get_texts():
        for soup in soups:
            text_containers = list(
                chain.from_iterable(
                    soup.find_all(attrs={"class": text_class}) for text_class in text_classes
                )
            )

            text_elements = list(
                chain.from_iterable(
                    container.find_all("p") for container in text_containers
                )
            )

            non_link_text_elements = [element for element in text_elements
                                      if not element.find_all("a")]

            texts = [element.text.strip() for element in non_link_text_elements]
            combined_text = "\n".join(texts)
            
            yield combined_text

    def get_image_srcs_list():
        # Since encoding a list into a DataFrame can get weird,
        # I will save the image list as a single string, 
        # with each image src on a separate line.
        # Then when downloading images, I can decode this back into a list.
        for soup in soups:
            images_srcs: list[str] = [image.get("src") for image in soup.find_all("img")]
            images_srcs = [
                f"https://ufc.com{src}" if not src.startswith("https") else src
                for src in images_srcs 
            ]

            yield "\n".join(images_srcs)
    
    def get_image_captions():
        for soup in soups:
            image_caption_elements = soup.find_all(attrs={"class": "field--name-image"})
            image_captions = [element.text.strip() for element in image_caption_elements]

            yield "\n".join(image_captions)

    return {
        "title": get_titles(),
        "description": get_descriptions(),
        "published_time": get_published_times(),
        "modified_time": get_modified_times(),
        "author": get_authors(),
        "social_media": get_social_medias(),
        "text": get_texts(),
        "images_srcs": get_image_srcs_list(),
        "images_captions": get_image_captions(),
    }

In [4]:
datas = get_page_datas(articles_df["content"])
for key in datas.keys():
    articles_df[key] = list(datas[key])

articles_df

,link,type,time_ago,headline,content,title,description,published_time,modified_time,author,social_media,text,images_srcs,images_captions
0,/news/gabriel-bonfim-leveled-up-legend-ufc-veg...,Athletes,4 hours ago,Gabriel Bonfim | Leveled Up By A Legend,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Gabriel Bonfim | Leveled Up By A Legend,Brazilian Welterweight Contender Is Still Grow...,2025-11-06 18:39:27-06:00,2025-11-06 19:05:11-06:00,Simon Head,simonheadsport,It’s often said that fighters learn more from ...,https://ufc.com/images/styles/background_image...,Gabriel Bonfim of Brazil punches Stephen Thomp...
1,/news/chris-padilla-blocking-out-the-noise-ufc...,Athletes,5 hours ago,Chris Padilla | Blocking Out The Noise,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Chris Padilla | Blocking Out The Noise,Lightweight Prospect Looks To Secure His Fourt...,2025-11-06 17:30:00-06:00,2025-11-06 17:35:33-06:00,Maddyn Johnstone,None,"For Chris Padilla, it doesn’t matter where he ...",https://ufc.com/images/styles/background_image...,Chris Padilla punches Jai Herbert in a lightwe...
2,/news/matt-schnell-honest-excited-and-dangerou...,Athletes,5 hours ago,"Matt Schnell | Honest, Excited, And Dangerous","\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...","Matt Schnell | Honest, Excited, And Dangerous","Veteran Flyweight Discusses Retirement, Return...",2025-11-06 17:14:00-06:00,2025-11-06 17:41:09-06:00,E. Spencer Kyte,spencerkyte,Matt Schnell is an interviewer’s dream; you as...,https://ufc.com/images/styles/background_image...,Matt Schnell elbows Jimmy Flick in a flyweight...
3,/news/tecia-pennington-crossroad-ufc-fight-nig...,Athletes,5 hours ago,Tecia Pennington | At A Crossroad,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Tecia Pennington | At A Crossroad,"Rankings Mainstay Talks Motherhood, Fighting M...",2025-11-06 16:50:19-06:00,2025-11-06 17:42:01-06:00,E. Spencer Kyte,spencerkyte,Tecia Pennington heads into her fight with Den...,https://ufc.com/images/styles/background_image...,Tecia Pennington kicks Luana Pinheiro of Brazi...
4,/news/uros-medic-back-track-ufc-fight-night-bo...,Athletes,5 hours ago,Uroš Medić Is Back On Track,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Uroš Medić Is Back On Track,Serbian Striker Has His Sights Set On The Welt...,2025-11-06 13:11:39-06:00,2025-11-06 16:41:33-06:00,Simon Head,simonheadsport,"At the start of 2025, Uroš Medić set himself t...",https://ufc.com/images/styles/background_image...,Uros Medic of Serbia drops Gilbert Urbina with...
5,/news/randy-brown-something-bigger-ufc-fight-n...,Athletes,11 hours ago,Randy Brown | Something Bigger,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Randy Brown | Something Bigger,"Veteran Talks Main Event Assignment, Providing...",2025-11-06 10:50:18-06:00,2025-11-06 10:34:28-06:00,E. Spencer Kyte,None,Randy Brown has been waiting for this moment f...,https://ufc.com/images/styles/background_image...,Randy Brown of Jamaica knees Nicolas Dalby of ...
6,/news/joseph-morales-all-way-back-ufc-vegas-11...,Athletes,1 day ago,Joseph Morales | All The Way Back,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Joseph Morales | All The Way Back,Recent TUF Winner Discusses Return To UFC Rost...,2025-11-05 17:10:08-06:00,2025-11-05 17:28:29-06:00,E. Spencer Kyte,spencerkyte,Joseph Morales didn’t really celebrate his vic...,https://ufc.com/images/styles/background_image...,Joseph Morales attempts to submit Roberto Sanc...
7,/news/malcolm-wellmaker-built-ground-bantamwei...,Athletes,1 day ago,Malcolm Wellmaker | Built From The Ground Up,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Malcolm Wellmaker | Built From The Ground Up,How a Rising Bantamweight Star Turned a Distan...,2025-11-05 11:27:38-06:00,2025-11-05 11:36:50-06:00,Kevin Schuster,None,"Earlier this year, bantamweight Malcolm Wellma...",https://ufc.com/images/styles/background_image...,Malcolm Wellmaker reacts after knocking out Kr...
8,/news/christian-leroy-duncan-settled-and-start...,Athletes,1 day ago,Christian Leroy Duncan | Settled In And Starti...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Christian Leroy Duncan | Settled In And Starti...,British Middleweight Talks Learning On The Job...,2025-11-05 11:13:53-06:00,2025-11-05 13:14:04-06:00,E. Spencer Kyte,spencerkyte,Here’s a very simple truth that doesn’t get ac...,https://ufc.com/images/styles/background_image...,Christian Leroy Duncan of England punches Eryk...
9,/news/adrian-yanez-reloaded-ufc-vegas-111,Athletes,3 weeks hence,Adrian Yanez | Reloaded,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Adrian Yanez | Reloaded,"After Nearly A Year Away, Bantamweight Standou...",2025-11-04 16:36:00-06:00,2025-11-06 10:57:10-06:00,E. Spencer Kyte,spencerkyte,The first two years of Adrian Yanez’ UFC caree...,https://ufc.com/images/styles/background_image...,Adrian Yanez punches Vinicius Salvador of Braz...
10,/news/fighters-on-the-rise-ufc-fight-night-bon...,Athletes,3 days ago,Fighters On The Rise | UFC Fight Night: Bonfim...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Fighters On The Rise | UFC Fight Night: Bonfim...,Highlighting Three Ascending Talents Set To Co...,2025-11-03 14:04:30-06:00,2025-11-04 12:28:42-06:00,E. Spencer Kyte,spencerkyte,Now that we’ve entered the penultimate month o...,https://ufc.com/images/styles/background_image...,Joseph Morales punches Alibi Idiris of Kazakst...
11,/news/fight-fight-preview-ufc-fight-night-bonf...,Fight Coverage,3 days ago,Fight By Fight Preview | UFC Fight Night: Bonf...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Fight By Fight Preview | UFC Fight Night: Bonf...,Detailing What’s On Tap And What’s At Stake At...,2025-11-03 12:16:47-06:00,2025-11-03 12:38:41-06:00,E. Spencer Kyte,spencerkyte,"Halloween just passed, which means chances are...",https://ufc.com/images/styles/background_image...,Randy Brown of Jamaica knees Nicolas Dalby of ...
12,/news/scorecard-ufc-fight-night-garcia-vs-onama,Fight Coverage,4 days ago,The Scorecard | UFC Fight Night: Garcia vs Onama,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",The Scorecard | UFC Fight Night: Garcia vs Onama,Take A Look At The Biggest Winners From UFC Fi...,2025-11-02 15:16:21-06:00,2025-11-02 15:35:02-06:00,Simon Head,simonheadsport,The Octagon returned home on Saturday night as...,https://ufc.com/images/styles/background_image...,Waldo Cortes Acosta of the Dominican Republic ...
13,/news/ufc-fight-night-garcia-vs-onama-main-car...,Results,5 days ago,Main Card Results | UFC Fight Night: Garcia vs...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Main Card Results | UFC Fight Night: Garcia vs...,"Get Live Results, Watch Post-Fight Interviews ...",2025-11-01 21:45:00-05:00,2025-11-03 12:47:48-06:00,None,None,Following an entertaining preliminary card sla...,https://ufc.com/images/styles/background_image...,
14,/news/bonus-coverage-2025-performance-fight-of...,Results,4 days ago,Bonus Coverage | UFC Fight Night: Garcia vs Onama,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Bonus Coverage | UFC Fight Night: Garcia vs Onama,The Fights & Performances That Warranted An Ex...,2025-11-01 21:30:00-05:00,2025-11-02 15:37:00-06:00,UFC Staff Report,None,A card that might have flown beneath the radar...,https://ufc.com/images/styles/background_image...,Steve Garcia punches David Onama of Uganda in ...
15,/news/ufc-fight-night-garcia-vs-onama-prelim-r...,Results,4 days ago,Prelim Results | UFC Fight Night: Garcia vs Onama,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Prelim Results | UFC Fight Night: Garcia vs Onama,"Get Live Results, Watch Post-Fight Interviews ...",2025-11-01 18:22:00-05:00,2025-11-01 20:51:04-05:00,E. Spencer Kyte,SpencerKyte,The action returned to UFC APEX on Saturday fo...,https://ufc.com/images/styles/background_image...,
16,/news/fight-by-fight-preview-ufc-fight-night-g...,Fight Coverage,5 days ago,UFC Tonight: Fight By Fight Preview | UFC Fight…,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",UFC Tonight: Fight By Fight Preview | UFC Figh...,Diving Into The Matchups Set To Hit The Octago...,2025-11-01 11:00:00-05:00,2025-11-01 11:17:58-05:00,E. Spencer Kyte,SpencerKyte,The action returns to UFC APEX this Saturday f...,https://ufc.com/images/styles/background_image...,David Onama punches Giga Chikadze in a feather...
17,/news/yadier-del-valle-no-fear-ufc-vegas-110,Athletes,6 days ago,Yadier del Valle | No Fear,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Yadier del Valle | No Fear,Undefeated Featherweight Exudes Confidence Ahe...,2025-10-31 14:54:00-05:00,2025-10-31 14:55:24-05:00,E. Spencer Kyte,spencerkyte,The present and forthcoming generation of tale...,https://ufc.com/images/styles/background_image...,Yadier del Valle of Cuba kicks Connor Matthews...
18,/news/themba-gorimbo-welcome-to-the-mamba-show...,Athletes,6 days ago,Themba Gorimbo: ‘Welcome To The Mamba Show’,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Themba Gorimbo: ‘Welcome To The Mamba Show’,"Ahead Of His First Fight Of 2025, Themba Gorim...",2025-10-31 08:00:00-05:00,2025-10-31 08:00:00-05:00,Zac Pacleb,ZacPacleb,Themba Gorimbo is keeping things short and swe...,https://ufc.com/images/styles/background_image...,Themba Gorimbo of Zimbabwe reacts after his kn...
19,/news/the-tao-of-allan-nascimento-ufc-vegas-110,Athletes,1 week ago,The Tao Of Allan Nascimento,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",The Tao Of Allan Nascimento,Brazilian Flyweight Shares His Thoughtful Outl...,2025-10-30 18:00:00-05:00,2025-10-31 19:25:35-05:00,E. Spencer Kyte,spencerkyte,If you were to write out a list of the most sk...,https://ufc.com/images/styles/background_image...,Allan Nascimento of Brazil reacts after his vi...
20,/news/phil-rowe-tired-of-fighting-himself-ufc-...,Athletes,1 week ago,Phil Rowe | Tired of Fighting Himself,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Phil Rowe | Tired of Fighting Himself,Welterweight Addresses Personal Frustrations W...,2025-10-30 15:41:46-05:00,2025-10-30 16:04:05-05:00,E. Spencer Kyte,spencerkyte,Phil Rowe sat at the table stationed in the me...,https://ufc.com/images/styles/background_image...,Phil Rowe punches Ange Loosa of the Congo in a...
21,/news/waldo-cortes-acosta-be-more-waldo-ufc-ve...,Athletes,1 week ago,Waldo Cortes Acosta | Be More Waldo,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Waldo Cortes Acosta | Be More Waldo,Top-10 Heavyweight Contender Has A Simple Plan...,2025-10-30 12:53:57-05:00,2025-10-30 13:01:02-05:00,Simon Head,simonheadsport,Waldo Cortes Acosta goes by the fighting monik...,https://ufc.com/images/styles/background_image...,Waldo Cortes Acosta punches Serghei Spivac in ...
22,/news/alice-ardelean-is-planning-her-big-move-...,Athletes,1 week ago,Alice Ardelean Is Planning Her Big Move,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Alice Ardelean Is Planning Her Big Move,With Ambitions Of Progressing Up The Strawweig...,2025-10-30 12:47:34-05:00,2025-10-30 12:53:39-05:00,Simon Head,simonheadsport,Alice Ardelean remains close to her Romanian r...,https://ufc.com/images/styles/background_image...,Alice Ardelean punches Rayanne dos Santos in a...
23,/news/ante-delija-making-waves,Athletes,1 week ago,Ante Delija | Making Waves,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Ante Delija | Making Waves,"Heavyweight Newcomer Talks Impressive Debut, T...",2025-10-30 12:44:00-05:00,2025-10-30 12:47:13-05:00,E. Spencer Kyte,spencerkyte,Making an immediate impact in the UFC is a cha...,https://ufc.com/images/styles/background_image...,Ante Delija of Croatia reacts after his TKO vi...
24,/news/ketlen-vieira-ready-claim-title-ufc-vega...,Athletes,1 week ago,Ketlen Vieira Is Ready To Claim Her Title Shot,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Ketlen Vieira Is Ready To Claim Her Title Shot,Longtime Women's Bantamweight Contender Plans ...,2025-10-30 10:00:06-05:00,2025-10-30 10:59:03-05:00,Simon Head,simonheadsport,"Ketlen Vieira has been in the UFC since 2016, ...",https://ufc.com/images/styles/background_image...,Ketlen Vieira (Photo by Cooper Neill/Zuffa LLC...
25,/news/norma-dumont-done-waiting-around-ufc-fig...,Athletes,1 week ago,Norma Dumont Is Done Waiting Around,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Norma Dumont Is Done Waiting Around,"Brazilian Contender Excited To Fight, Ready To...",2025-10-29 15:29:04-05:00,2025-10-29 17:43:25-05:00,E. Spencer Kyte,spencerkyte,"Last September, Norma Dumont waltzed into the ...",https://ufc.com/images/styles/background_image...,Norma Dumont of Brazil strikes Irene Aldana of...
26,/news/david-onama-excited-but-also-expected-ve...,Athletes,1 week ago,"David Onama | Excited, But Also Expected","\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...","David Onama | Excited, But Also Expected",First-Time Headliner Discusses Saturday’s Main...,2025-10-29 14:43:00-05:00,2025-10-29 14:45:39-05:00,E. Spencer Kyte,spencerkyte,David Onama hadn’t been to sign posters for th...,https://ufc.com/images/styles/background_image...,David Onama of Uganda knocks out Gabriel Santo...
27,/news/donte-johnson-clocking-in-ufc-vegas-110,Athletes,1 week ago,Donte Johnson | Clocking In,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Donte Johnson | Clocking In,Dana White’s Contender Series Grad Talks Rapid...,2025-10-29 12:05:00-05:00,2025-10-29 12:11:10-05:00,E. Spencer Kyte,spencerkyte,Donte Johnson claimed his place on the UFC ros...,https://ufc.com/images/styles/background_image...,Donte Johnson reacts after defeating Darion Ab...
28,/news/10-get-ready-for-a-november-to-remember-...,Athletes,1 week ago,The 10 | Get Ready For A November To Remember ...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",The 10 | Get Ready For A November To Remember ...,Coming Month Offers Heaps Of High-Level Matchu...,2025-10-29 11:54:58-05:00,2025-10-29 16:03:43-05:00,E. Spencer Kyte,spencerkyte,"November is stacked. Normally, I would look to...",https://ufc.com/images/styles/background_image...,Ketlen Vieira of Brazil punches Macy Chiasson ...
29,/news/fighters-rise-ufc-fight-night-garcia-vs-...,Athletes,1 week ago,Fighters On The Rise | UFC Fight Night: Garcia...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Fighters On The Rise | UFC Fight Night: Garcia...,Highlighting Three Athletes On The Come-Up Hea...,2025-10-28 12:22:34-05:00,2025-10-29 17:06:21-05:00,E. Spencer Kyte,None,Fatima Kline. Jean Silva. David Martinez. Aiem...,https://ufc.com/images/styles/background_image...,Norma Dumont strikes Irene Aldana in a bantamw...
30,/news/steve-garcia-real-recognizes-real-ufc-fi...,Athletes,1 week ago,Steve Garcia | Real Recognizes Real,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Steve Garcia | Real Recognizes Real,Streaking Featherweight Continues Quiet March ...,2025-10-28 10:48:44-05:00,2025-10-29 15:21:57-05:00,E. Spencer Kyte,None,Steve Garcia’s career is currently bookended b...,https://ufc.com/images/styles/background_image...,Steve Garcia kicks Calvin Kattar in a featherw...
31,/news/monthly-report-october-2025-ufc-jourdain...,Athletes,1 week ago,Monthly Report | October 2025,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Monthly Report | October 2025,Highlighting Standout Performances From Inside...,2025-10-27 12:58:34-05:00,2025-10-27 14:54:40-05:00,E. Spencer Kyte,spencerkyte,The UFC is in that non-stop part of the fall s...,https://ufc.com/images/styles/background_image...,Charles Jourdain of Canada secures a guillotin...
32,/news/bigger-picture-ufc-321-aspinall-vs-gane,Fight Coverage,1 week ago,The Bigger Picture | UFC 321: Aspinall vs Gane,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",The Bigger Picture | UFC 321: Aspinall vs Gane,An Entertaining Night Ended In A Manner No One...,2025-10-27 10:40:45-05:00,2025-10-27 11:11:05-05:00,E. Spencer Kyte,None,The UFC’s annual October pay-per-view event in...,https://ufc.com/images/styles/background_image...,The UFC heavyweight championship fight between...
33,/news/ufc-321-aspinall-vs-gane-event-tonight-m...,Results,1 week ago,Main Card Results | UFC 321: Aspinall vs Gane,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Main Card Results | UFC 321: Aspinall vs Gane,"Get Live Results, Watch Post-Fight Interviews ...",2025-10-25 17:03:00-05:00,2025-10-27 10:53:20-05:00,E. Spencer Kyte,SpencerKyte,The UFC 321 pay-per-view main card at Etihad A...,https://ufc.com/images/styles/background_image...,
34,/news/ufc-321-aspinall-vs-gane-event-tonight-p...,Results,1 week ago,Prelim Results | UFC 321: Aspinall vs Gane,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Prelim Results | UFC 321: Aspinall vs Gane,"Get Live Results, Watch Post-Fight Interviews ...",2025-10-25 13:15:00-05:00,2025-10-25 16:38:30-05:00,E. Spencer Kyte,SpencerKyte,The UFC returned to Etihad Arena in Abu Dhabi ...,https://ufc.com/images/styles/background_image...,
35,/news/fight-by-fight-preview-ufc-321-aspinall-...,Fight Coverage,1 week ago,UFC Today: Fight By Fight Preview | UFC 321:…,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",UFC Today: Fight By Fight Preview | UFC 321: A...,Setting The Table For Saturday’s Epic Night Of...,2025-10-25 08:18:00-05:00,2025-10-25 08:19:18-05:00,E. Spencer Kyte,SpencerKyte,The UFC makes its second trip to Abu Dhabi thi...,https://ufc.com/images/styles/background_image...,Ciryl Gane punches Alexander Volkov during a h...
36,/news/junyong-park-hungry-for-more-ufc-321,Athletes,1 week ago,Junyong Park | Hungry For More,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Junyong Park | Hungry For More,Playful South Korean Middleweight Ready To Com...,2025-10-24 18:37:16-05:00,2025-10-24 18:18:15-05:00,E. Spencer Kyte,None,Upon sitting down to speak with JunYong Park e...,https://ufc.com/images/styles/background_image...,unYong Park of South Korea reacts after his vi...
37,/news/seriously-do-not-blink-when-tom-aspinall...,Athletes,1 week ago,Seriously: Do Not Blink When Tom Aspinall And ...,"\n\n\n\n\n\n<!DOCTYPE html>\n<html lang=""en-ca...",Seriously: Do Not Blink When Tom Aspinall And ...,The Heavyweight Title Bout Between Tom Aspinal...,2025-10-24 11:19:02-05:00,2025-10-24 11:49:09-05:00,Zac Paceb,ZacPacleb,Few titles in combat sports carry the same pom...,https://ufc.com/images/styles/background_image...,Tom Aspinall of England faces Sergei Pavlovich...

In [5]:
with_data_filename = f"{csv_filename}_with_data.csv"
articles_df\
    .drop("content", axis=1)\
    .set_index("link")\
    .to_csv(with_data_filename)

print("Saved article metadata and contents to", with_data_filename)

Saved article metadata and contents to ./article_links_06-11-25_20-40-38_with_contents_with_data.csv

In [6]:
new_csv_filename = csv_filename.replace("with_contents", "with_only_metadata")

articles_df\
    .drop("content", axis=1)\
    .drop("text", axis=1)\
    .drop("images_srcs", axis=1)\
    .drop("images_captions", axis=1)\
    .set_index("link")\
    .to_csv(f"{new_csv_filename}.csv")

print("Saved article metadata to", new_csv_filename)

Saved article metadata to ./article_links_06-11-25_20-40-38_with_only_metadata

In [7]:
folder = "./articles"
os.makedirs(folder, exist_ok=True)

for row in articles_df.iloc:
    filename = get_page_name(row["link"])
    
    try:
        with open(f"{folder}/{filename}.txt", "w", encoding="utf-8") as file:
            file.write(row["text"])
    except Exception as e:
        print("Error saving", filename)
        print(e)