In [1]:
import pandas as pd

In [5]:
links = pd.read_csv("./article_links_12-09-25_02-14-55.csv").set_index("index")
links

,type,time_ago,title,link
index,,,,
0,Fight Coverage,2 hours ago,Press Conference Highlights | Canelo vs Crawford,https://www.ufc.com/video/150879
1,Athletes,2 hours ago,Alexander Hernandez Feels Like He Has Nothing ...,https://www.ufc.com/news/alexander-hernandez-f...
2,Athletes,2 hours ago,Tatiana Suarez Is Ready To Show Her Best Self,https://www.ufc.com/news/tatiana-suarez-is-rea...
3,Fight Coverage,6 hours ago,Pre-Fight Press Conference | Canelo vs Crawford,https://www.ufc.com/video/150864
4,Licensed,7 hours ago,Discover The Latest Noche UFC Merch &amp; Gear...,https://www.ufc.com/news/discover-latest-noche...
...,...,...,...,...
4808,Interviews,1 year ago,ChangHo Lee Octagon Interview | UFC Saudi Arabia,https://www.ufc.com/video/140129
4809,Announcements,1 year ago,"Stancé Launches Globally, Teams Up with UFC to…",https://www.ufc.com/news/stance-launches-globa...
4810,Athletes,1 year ago,A Dream Within Reach For ChangHo Lee,https://www.ufc.com/news/dream-within-reach-ch...
4811,Fight Coverage,1 year ago,Cold Open | UFC Saudi Arabia,https://www.ufc.com/video/140128
4812,Athletes,1 year ago,"Teila Tuli, 1968-2024",https://www.ufc.com/news/taylor-wily-teila-tul...

In [12]:
first_article_2025_title = "Fighters On The Rise 2025 | Part Two"
first_article_2025_index = links[links["title"] == first_article_2025_title].index.values[0]

links_2025 = links[links.index <= first_article_2025_index]
links_2025

,type,time_ago,title,link
index,,,,
0,Fight Coverage,2 hours ago,Press Conference Highlights | Canelo vs Crawford,https://www.ufc.com/video/150879
1,Athletes,2 hours ago,Alexander Hernandez Feels Like He Has Nothing ...,https://www.ufc.com/news/alexander-hernandez-f...
2,Athletes,2 hours ago,Tatiana Suarez Is Ready To Show Her Best Self,https://www.ufc.com/news/tatiana-suarez-is-rea...
3,Fight Coverage,6 hours ago,Pre-Fight Press Conference | Canelo vs Crawford,https://www.ufc.com/video/150864
4,Licensed,7 hours ago,Discover The Latest Noche UFC Merch &amp; Gear...,https://www.ufc.com/news/discover-latest-noche...
...,...,...,...,...
2774,Interviews,8 months ago,Umar Nurmagomedov Previews First Title Shot | ...,https://www.ufc.com/video/144696
2775,ESPN MMA,8 months ago,Bold 2025 Predications From Good Guy / Bad Guy,https://www.ufc.com/video/144682
2776,Power Slap,8 months ago,SUPER HEAVYWEIGHT CHAMPIONSHIP REMATCH TO HEAD...,https://www.ufc.com/news/super-heavyweight-cha...
2777,Fight Coverage,8 months ago,The 10 | Jumping Into The New Year Inside The ...,https://www.ufc.com/news/10-jumping-new-year-i...
2778,Athletes,8 months ago,Fighters On The Rise 2025 | Part Two,https://www.ufc.com/news/fighters-rise-2025-pa...

In [14]:
filtered_types_links = links_2025[
    (links_2025["type"] == "Athletes") 
    | (links_2025["type"] == "Results") 
    | (links_2025["type"] == "Fight Coverage") 
    | (links_2025["type"] == "Fight Preview")
]
filtered_types_links

,type,time_ago,title,link
index,,,,
0,Fight Coverage,2 hours ago,Press Conference Highlights | Canelo vs Crawford,https://www.ufc.com/video/150879
1,Athletes,2 hours ago,Alexander Hernandez Feels Like He Has Nothing ...,https://www.ufc.com/news/alexander-hernandez-f...
2,Athletes,2 hours ago,Tatiana Suarez Is Ready To Show Her Best Self,https://www.ufc.com/news/tatiana-suarez-is-rea...
3,Fight Coverage,6 hours ago,Pre-Fight Press Conference | Canelo vs Crawford,https://www.ufc.com/video/150864
7,Fight Coverage,10 hours ago,Main Event Preview | Canelo vs Crawford,https://www.ufc.com/video/150871
...,...,...,...,...
2770,Fight Coverage,8 months ago,Fight By Fight Preview | UFC Fight Night: Dern...,https://www.ufc.com/news/fight-fight-preview-u...
2771,Athletes,8 months ago,Christian Rodriguez | This One Means Everything,https://www.ufc.com/news/christian-rodriguez-o...
2773,Fight Coverage,8 months ago,Main Event Spotlight | UFC Fight Night: Dern vs…,https://www.ufc.com/news/main-event-spotlight-...
2777,Fight Coverage,8 months ago,The 10 | Jumping Into The New Year Inside The ...,https://www.ufc.com/news/10-jumping-new-year-i...
2778,Athletes,8 months ago,Fighters On The Rise 2025 | Part Two,https://www.ufc.com/news/fighters-rise-2025-pa...

In [ ]:
athlete_links = links[links["type"] == "Athletes"]
athlete_links

In [ ]:
athlete_articles = athlete_links[athlete_links["link"].str.contains("news")]
athlete_articles

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.remote.webelement import WebElement

In [ ]:
import re

In [ ]:
credit_pattern = (
    r"^By\s+(?P<name>[^,•]+)"
    r"(?:,\s+on\s+(?P<social_media>\w+):?\s+@(?P<handle>\S+))?"
    r"\s+•\s+(?P<date>.+)$"
)

In [ ]:
test_credit = "BY THOMAS GERBASI, ON X @TGERBASI • SEP. 12, 2025"

In [ ]:
def scrape_article(link: str):
    driver = webdriver.Chrome()
    driver.get(link)

    try:
        title = driver\
            .find_element(By.CLASS_NAME, "field--name-node-title")\
            .find_element(By.TAG_NAME, "h1")\
            .get_attribute("innerHTML")\
            .strip()\
            .replace("\n", "")
        
        subtitle = driver\
            .find_element(By.CLASS_NAME, "field--name-subtitle")\
            .get_attribute("innerHTML")\
            .strip()\
            .replace("\n", "")
        
        credit = driver\
            .find_element(By.CLASS_NAME, "c-hero__article-credit")\
            .get_attribute("innerHTML")\
            .strip()\
            .replace("\n", "")

        name = None
        social_media = None
        handle = None
        date = None

        credit_match = re.search(credit_pattern, credit)
        if credit_match:
            name = credit_match.group("name")
            social_media = credit_match.group("social_media")
            handle = credit_match.group("handle")
            date = credit_match.group("date")
        
        content = driver.find_element(By.CLASS_NAME, "l-two-col__content")
        texts = [
            text.get_attribute("innerHTML").strip()
            for text in content.find_elements(By.CSS_SELECTOR, "p, a")
        ]

        return {
            'title': title,
            'subtitle': subtitle,
            'credit': credit,
            'name': name,
            'social_media': social_media,
            'handle': handle,
            'date': date,
            'texts': texts
        }

    finally:
        driver.quit()

In [ ]:
test_article_scraped = scrape_article("https://www.ufc.com/news/alexander-hernandez-feels-like-he-has-nothing-to-lose-noche-ufc")
test_article_scraped

In [ ]:
test_article_scraped["texts"]