In [7]:
import pandas as pd

In [8]:
links = pd.read_csv("./article_links_12-09-25_02-14-55.csv")
links

,Unnamed: 0,type,time_ago,title,link
0,0,Fight Coverage,2 hours ago,Press Conference Highlights | Canelo vs Crawford,https://www.ufc.com/video/150879
1,1,Athletes,2 hours ago,Alexander Hernandez Feels Like He Has Nothing ...,https://www.ufc.com/news/alexander-hernandez-f...
2,2,Athletes,2 hours ago,Tatiana Suarez Is Ready To Show Her Best Self,https://www.ufc.com/news/tatiana-suarez-is-rea...
3,3,Fight Coverage,6 hours ago,Pre-Fight Press Conference | Canelo vs Crawford,https://www.ufc.com/video/150864
4,4,Licensed,7 hours ago,Discover The Latest Noche UFC Merch &amp; Gear...,https://www.ufc.com/news/discover-latest-noche...
...,...,...,...,...,...
4808,4808,Interviews,1 year ago,ChangHo Lee Octagon Interview | UFC Saudi Arabia,https://www.ufc.com/video/140129
4809,4809,Announcements,1 year ago,"Stancé Launches Globally, Teams Up with UFC to…",https://www.ufc.com/news/stance-launches-globa...
4810,4810,Athletes,1 year ago,A Dream Within Reach For ChangHo Lee,https://www.ufc.com/news/dream-within-reach-ch...
4811,4811,Fight Coverage,1 year ago,Cold Open | UFC Saudi Arabia,https://www.ufc.com/video/140128
4812,4812,Athletes,1 year ago,"Teila Tuli, 1968-2024",https://www.ufc.com/news/taylor-wily-teila-tul...

In [9]:
athlete_links = links[links["type"] == "Athletes"]
athlete_links

,Unnamed: 0,type,time_ago,title,link
1,1,Athletes,2 hours ago,Alexander Hernandez Feels Like He Has Nothing ...,https://www.ufc.com/news/alexander-hernandez-f...
2,2,Athletes,2 hours ago,Tatiana Suarez Is Ready To Show Her Best Self,https://www.ufc.com/news/tatiana-suarez-is-rea...
10,10,Athletes,1 day ago,Dustin Stoltzfus: 'It's Now Or Never',https://www.ufc.com/news/dustin-stoltzfus-its-...
12,12,Athletes,1 day ago,Diego Lopes Knows He Is A High-Level Fighter,https://www.ufc.com/news/diego-lopes-knows-he-...
14,14,Athletes,1 day ago,"Zachary Reese | All Gas, No Brakes",https://www.ufc.com/news/zachary-reese-all-gas...
...,...,...,...,...,...
4781,4781,Athletes,1 year ago,People Are Rightfully Taking Notice Of Payton ...,https://www.ufc.com/news/people-taking-notice-...
4783,4783,Athletes,1 year ago,Jiří Procházka Career Highlights,https://www.ufc.com/news/jiri-prochazka-career...
4788,4788,Athletes,1 year ago,Joe Pyfer Continues To Grow,https://www.ufc.com/news/joe-pyfer-continues-t...
4810,4810,Athletes,1 year ago,A Dream Within Reach For ChangHo Lee,https://www.ufc.com/news/dream-within-reach-ch...
4812,4812,Athletes,1 year ago,"Teila Tuli, 1968-2024",https://www.ufc.com/news/taylor-wily-teila-tul...

In [49]:
athlete_articles = athlete_links[athlete_links["link"].str.contains("news")]
athlete_articles

,Unnamed: 0,type,time_ago,title,link
1,1,Athletes,2 hours ago,Alexander Hernandez Feels Like He Has Nothing ...,https://www.ufc.com/news/alexander-hernandez-f...
2,2,Athletes,2 hours ago,Tatiana Suarez Is Ready To Show Her Best Self,https://www.ufc.com/news/tatiana-suarez-is-rea...
10,10,Athletes,1 day ago,Dustin Stoltzfus: 'It's Now Or Never',https://www.ufc.com/news/dustin-stoltzfus-its-...
12,12,Athletes,1 day ago,Diego Lopes Knows He Is A High-Level Fighter,https://www.ufc.com/news/diego-lopes-knows-he-...
14,14,Athletes,1 day ago,"Zachary Reese | All Gas, No Brakes",https://www.ufc.com/news/zachary-reese-all-gas...
...,...,...,...,...,...
4781,4781,Athletes,1 year ago,People Are Rightfully Taking Notice Of Payton ...,https://www.ufc.com/news/people-taking-notice-...
4783,4783,Athletes,1 year ago,Jiří Procházka Career Highlights,https://www.ufc.com/news/jiri-prochazka-career...
4788,4788,Athletes,1 year ago,Joe Pyfer Continues To Grow,https://www.ufc.com/news/joe-pyfer-continues-t...
4810,4810,Athletes,1 year ago,A Dream Within Reach For ChangHo Lee,https://www.ufc.com/news/dream-within-reach-ch...
4812,4812,Athletes,1 year ago,"Teila Tuli, 1968-2024",https://www.ufc.com/news/taylor-wily-teila-tul...

In [11]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.remote.webelement import WebElement

In [18]:
import re

In [32]:
credit_pattern = (
    r"^By\s+(?P<name>[^,•]+)"
    r"(?:,\s+on\s+(?P<social_media>\w+):?\s+@(?P<handle>\S+))?"
    r"\s+•\s+(?P<date>.+)$"
)

In [ ]:
test_credit = "BY THOMAS GERBASI, ON X @TGERBASI • SEP. 12, 2025"

In [52]:
def scrape_article(link: str):
    driver = webdriver.Chrome()
    driver.get(link)

    try:
        title = driver\
            .find_element(By.CLASS_NAME, "field--name-node-title")\
            .find_element(By.TAG_NAME, "h1")\
            .get_attribute("innerHTML")\
            .strip()\
            .replace("\n", "")
        
        subtitle = driver\
            .find_element(By.CLASS_NAME, "field--name-subtitle")\
            .get_attribute("innerHTML")\
            .strip()\
            .replace("\n", "")
        
        credit = driver\
            .find_element(By.CLASS_NAME, "c-hero__article-credit")\
            .get_attribute("innerHTML")\
            .strip()\
            .replace("\n", "")

        name = None
        social_media = None
        handle = None
        date = None

        credit_match = re.search(credit_pattern, credit)
        if credit_match:
            name = credit_match.group("name")
            social_media = credit_match.group("social_media")
            handle = credit_match.group("handle")
            date = credit_match.group("date")
        
        content = driver.find_element(By.CLASS_NAME, "l-two-col__content")
        texts = [
            text.get_attribute("innerHTML").strip()
            for text in content.find_elements(By.CSS_SELECTOR, "p, a")
        ]

        return {
            'title': title,
            'subtitle': subtitle,
            'credit': credit,
            'name': name,
            'social_media': social_media,
            'handle': handle,
            'date': date,
            'texts': texts
        }

    finally:
        driver.quit()

In [54]:
test_article_scraped = scrape_article("https://www.ufc.com/news/alexander-hernandez-feels-like-he-has-nothing-to-lose-noche-ufc")
test_article_scraped

{'title': 'Alexander Hernandez Feels Like He Has Nothing To Lose',
 'subtitle': 'After A Massive Knockout Win, Alexander Hernandez Is Hoping To Give The San Antonio Crowd Plenty To Cheer About On September 13',
 'credit': 'By Thomas Gerbasi, on X @tgerbasi • Sep. 12, 2025',
 'name': 'Thomas Gerbasi',
 'social_media': 'X',
 'handle': 'tgerbasi',
 'date': 'Sep. 12, 2025',
 'texts': ['If Alexander Hernandez was like the rest of us, he might have scored a first-round knockout over Chase Hooper last month and sat out the rest of the year. Instead, the newly minted “El Gran Chango” will put his three-fight winning streak on the line against Diego Ferreira this week in San Antonio.',
  'Why?',
  "“Just strike while that mother**ker's hot,” he laughed.",
  '<a href="https://www.ufc.com/tunein"><strong>Tune-In Information For Noche UFC And Canelo vs Crawford</strong></a>',
  '<strong>Tune-In Information For Noche UFC And Canelo vs Crawford</strong>',
  'But when the possibility of taking that winning streak into 2026 while eating like a fat kid through Thanksgiving and Christmas was brought up, he admits it did cross his mind. But getting through the Hooper fight unscathed and feeling as good as he ever has in the Octagon made his decision to get right back to work the right one.',
  'Continue watching',
  'Upgrade licence',
  "“I went to bed, didn't think about it all the next day, then the day after, I woke up and it just hit me,” he said. “I was like, man, you’ve got to do this. This is an opportunity and a half and I dunno whether it’s manifestation or just a good narrative, but I like the part I'm playing, so I'm going to keep playing it.”",
  'And he gets to play it in his hometown of San Antonio. It was always the dream gig, but with his fight against Hooper taking place less than a month before, he rightfully assumed it wasn’t going to happen. But then it did.',
  "“Lo and behold, we get a real clean first round finish and I'm like, ‘oh s**t, there's a chance I might fight on Noche,” said Hernandez. “And a part of me just wanted to rest on my laurels for a second and enjoy it. But man, it's juicy. And again, you’ve got to strike with the iron's hot because it isn't going to sizzle for long, so you got to take advantage. And I feel like it's a great opponent coming off a three-fight win streak. You can't ask for a better matchup. And I'm healthy and well and I'm hungry. It's a good opportunity, and I feel like I'm already winning. Like I said, whoever's writing this script, I like the part I'm playing, I'm going to keep playing it, and it's almost like we kind of lined up this narration. I'm just going to keep playing the character. So I don't think we have anything to lose.”",
  "It's been a long time since the 32-year-old has felt this way. After three consecutive wins in his return to the lightweight division after a brief stint at 145 pounds, it’s easy to forget a 1-4 stretch from 2022 that had everyone questioning what had happened to the kid who burst on the UFC scene in 2018 with a 42-second knockout of Beneil Dariush. But with a change of scenery in his training life, he’s got his mojo back.",
  '<strong>FOLLOW @UFCNEWS: </strong><a href="https://www.facebook.com/ufcnews/"><strong>On Facebook</strong></a><strong> </strong>|<strong> </strong><a href="https://www.instagram.com/ufcnews"><strong>On Instagram</strong></a><strong> </strong>|<strong> </strong><a href="https://x.com/UFCNews"><strong>On X</strong></a> | <a href="https://www.threads.net/@ufcnews"><strong>On Threads</strong></a>',
  '<strong>On Facebook</strong>',
  '<strong>On Instagram</strong>',
  '<strong>On X</strong>',
  '<strong>On Threads</strong>',
  "“It's been a minute because even the last couple of wins I was still gritting through 'em and I had to kind of recapitulate myself personally and just organize and get a good drive,” said Hernandez. “But man, we've got a great squad and it's family. And I feel like with that great squad, we prepare so well, we're so efficient, and I don't feel nearly as burned out as I would feel before. I feel like the place that we're at right now, we're good for each other, we're good to each other, and I think it shows.”",
  'The team name seemingly changes with each fighter’s walk to the Octagon, but this weekend, Hernandez will have teammate Luis Gurule on the card with him, and Brandon Royval, Clay Matza and Jason Yerrington manning the corner. It’s all he needs.',
  "“I think it's a small, tailored work,” Hernandez said of the new training philosophy in Colorado. “We're not doing anything superfluous. There's nothing extra. We Trimmed the fat for that Hooper fight. I trained probably less than I've ever trained for any fight, but it was just so intentional. All the work we were doing was intentional. And again, all that extra energy just goes back into recentering yourself, calming your nervous system, and staying level, mentally and physically.”",
  '<a href="https://www.ufc.com/news/fight-fight-preview-noche-ufc-lopes-vs-silva"><strong>Noche UFC Full Fight Card Preview</strong></a>',
  '<strong>Noche UFC Full Fight Card Preview</strong>',
  'The proof is on the won-loss record, and dare I say, the Alexander Hernandez of 2018 is back?',
  "“Oh man,” he laughs. “2018 was all balls and brass. This Hernandez has got some savvy and some real veteran s**t to him. So I would say I'm a far more refined version of that guy. And far more dangerous.”",
  '<em>Don\'t miss a moment of </em><a href="https://www.ufc.com/event/ufc-fight-night-september-13-2025"><em><strong>Noche UFC: Lopes vs Silva</strong></em></a><em>, live from Frost Bank Center in San Antonio, Texas on September 13, 2025. Prelims start at 3pm ET/12pm PT, followed by the main card at 6pm ET/3pm PT.</em>',
  '<em><strong>Noche UFC: Lopes vs Silva</strong></em>',
  'Noche UFC']}

In [55]:
test_article_scraped["texts"]

['If Alexander Hernandez was like the rest of us, he might have scored a first-round knockout over Chase Hooper last month and sat out the rest of the year. Instead, the newly minted “El Gran Chango” will put his three-fight winning streak on the line against Diego Ferreira this week in San Antonio.',
 'Why?',
 "“Just strike while that mother**ker's hot,” he laughed.",
 '<a href="https://www.ufc.com/tunein"><strong>Tune-In Information For Noche UFC And Canelo vs Crawford</strong></a>',
 '<strong>Tune-In Information For Noche UFC And Canelo vs Crawford</strong>',
 'But when the possibility of taking that winning streak into 2026 while eating like a fat kid through Thanksgiving and Christmas was brought up, he admits it did cross his mind. But getting through the Hooper fight unscathed and feeling as good as he ever has in the Octagon made his decision to get right back to work the right one.',
 'Continue watching',
 'Upgrade licence',
 "“I went to bed, didn't think about it all the next day, then the day after, I woke up and it just hit me,” he said. “I was like, man, you’ve got to do this. This is an opportunity and a half and I dunno whether it’s manifestation or just a good narrative, but I like the part I'm playing, so I'm going to keep playing it.”",
 'And he gets to play it in his hometown of San Antonio. It was always the dream gig, but with his fight against Hooper taking place less than a month before, he rightfully assumed it wasn’t going to happen. But then it did.',
 "“Lo and behold, we get a real clean first round finish and I'm like, ‘oh s**t, there's a chance I might fight on Noche,” said Hernandez. “And a part of me just wanted to rest on my laurels for a second and enjoy it. But man, it's juicy. And again, you’ve got to strike with the iron's hot because it isn't going to sizzle for long, so you got to take advantage. And I feel like it's a great opponent coming off a three-fight win streak. You can't ask for a better matchup. And I'm healthy and well and I'm hungry. It's a good opportunity, and I feel like I'm already winning. Like I said, whoever's writing this script, I like the part I'm playing, I'm going to keep playing it, and it's almost like we kind of lined up this narration. I'm just going to keep playing the character. So I don't think we have anything to lose.”",
 "It's been a long time since the 32-year-old has felt this way. After three consecutive wins in his return to the lightweight division after a brief stint at 145 pounds, it’s easy to forget a 1-4 stretch from 2022 that had everyone questioning what had happened to the kid who burst on the UFC scene in 2018 with a 42-second knockout of Beneil Dariush. But with a change of scenery in his training life, he’s got his mojo back.",
 '<strong>FOLLOW @UFCNEWS: </strong><a href="https://www.facebook.com/ufcnews/"><strong>On Facebook</strong></a><strong> </strong>|<strong> </strong><a href="https://www.instagram.com/ufcnews"><strong>On Instagram</strong></a><strong> </strong>|<strong> </strong><a href="https://x.com/UFCNews"><strong>On X</strong></a> | <a href="https://www.threads.net/@ufcnews"><strong>On Threads</strong></a>',
 '<strong>On Facebook</strong>',
 '<strong>On Instagram</strong>',
 '<strong>On X</strong>',
 '<strong>On Threads</strong>',
 "“It's been a minute because even the last couple of wins I was still gritting through 'em and I had to kind of recapitulate myself personally and just organize and get a good drive,” said Hernandez. “But man, we've got a great squad and it's family. And I feel like with that great squad, we prepare so well, we're so efficient, and I don't feel nearly as burned out as I would feel before. I feel like the place that we're at right now, we're good for each other, we're good to each other, and I think it shows.”",
 'The team name seemingly changes with each fighter’s walk to the Octagon, but this weekend, Hernandez will have teammate Luis Gurule on the card with him, and Brandon Royval, Clay Matza and Jason Yerrington manning the corner. It’s all he needs.',
 "“I think it's a small, tailored work,” Hernandez said of the new training philosophy in Colorado. “We're not doing anything superfluous. There's nothing extra. We Trimmed the fat for that Hooper fight. I trained probably less than I've ever trained for any fight, but it was just so intentional. All the work we were doing was intentional. And again, all that extra energy just goes back into recentering yourself, calming your nervous system, and staying level, mentally and physically.”",
 '<a href="https://www.ufc.com/news/fight-fight-preview-noche-ufc-lopes-vs-silva"><strong>Noche UFC Full Fight Card Preview</strong></a>',
 '<strong>Noche UFC Full Fight Card Preview</strong>',
 'The proof is on the won-loss record, and dare I say, the Alexander Hernandez of 2018 is back?',
 "“Oh man,” he laughs. “2018 was all balls and brass. This Hernandez has got some savvy and some real veteran s**t to him. So I would say I'm a far more refined version of that guy. And far more dangerous.”",
 '<em>Don\'t miss a moment of </em><a href="https://www.ufc.com/event/ufc-fight-night-september-13-2025"><em><strong>Noche UFC: Lopes vs Silva</strong></em></a><em>, live from Frost Bank Center in San Antonio, Texas on September 13, 2025. Prelims start at 3pm ET/12pm PT, followed by the main card at 6pm ET/3pm PT.</em>',
 '<em><strong>Noche UFC: Lopes vs Silva</strong></em>',
 'Noche UFC']